### ISSUE TITLE
installConfig crashes on new configuration

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/distro_helper#3]
Ran into an issue on kmc when installing brand new config with installConfig:

> >  [error]  TypeError: Argument 2 passed to Drupal\Core\Config\FileStorage::write() must be of the type array, bool given, called in /Users/gcb/Sites/kmc-tester-025/web/modules/contrib/distro_helper/src/DistroHelperUpdates.php on line 139 in Drupal\Core\Config\FileStorage->write() (line 141 of /Users/gcb/Sites/kmc-tester-025/web/core/lib/Drupal/Core/Config/FileStorage.php) #0 /Users/gcb/Sites/kmc-tester-025/web/modules/contrib/distro_helper/src/DistroHelperUpdates.php(139): Drupal\Core\Config\FileStorage->write('views.view.kmc_...', false)

This is on kmc-tester, which doesn't auto-export config. The new configuration seems to save just fine, but when trying to export it, this line calls $active_storage->read($configname)
https://github.com/thinkshout/distro_helper/blob/main/src/DistroHelperUpdates.php#L139

and it returns FALSE.

It seems like removing that line has 0 impact, so I'm going to try that, but not confident it's the right plan.

**Comment by mariacha** [comment]
We should just be able to wrap this in a boolean:

```
$active_storage_item = $active_storage->read($config_name);


if($active_storage_item){
   // Find out which config was saved.
    $sync_storage->write($config_name, $active_storage->read($config_name));

    // Export configuration collections.
    foreach ($active_storage->getAllCollectionNames() as $collection) {
      $active_collection = $active_storage->createCollection($collection);
      $sync_collection = $sync_storage->createCollection($collection);
      $sync_collection->write($config_name, $active_collection->read($config_name));
    }
}
```

That being said, what it's doing here is trying to read a value from the database and not finding it. So somewhere we're trying to export config from the database to the `/config` directory before the item is in the database. Is there any chance the config isn't named correctly or some such?
