### ISSUE TITLE
Strange error when Language module is enabled

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/distro_helper#6]
Sites with the Language module installed save configurations into "Language" folders. At least on D9!

When using this utility on those sites, it seems to try to write config out to these directories in addition to the /config directory, and you see errors like this one:
`>  [error]  Could not write the ../config/language/zxx/pathauto.pattern.event_subpage.yml file. Did it successfully save to the database?`

The directory `config/language/zxx` exists, so it's not an issue with trying to write a nonexistent directory.

**Comment by unclegcb** [comment]
@mariacha have you seen this one yet?

**Comment by mariacha** [comment]
I haven't seen this error, but that's not surprising, since I didn't test it with languages at all. I probably misunderstood when this is necessary.
